/**
 * Shared types for generators
 * Generated by strapi2front
 */

import type { ParsedSchema } from '@strapi2front/core';

/**
 * Supported output formats
 */
export type OutputFormat = 'typescript' | 'jsdoc';

/**
 * Supported frameworks
 */
export type Framework = 'astro' | 'nextjs' | 'nuxt' | 'generic';

/**
 * Supported Strapi versions
 */
export type StrapiVersion = 'v4' | 'v5';

/**
 * Base generator options
 */
export interface BaseGeneratorOptions {
  outputDir: string;
  strapiVersion?: StrapiVersion;
}

/**
 * Type generator options
 */
export interface TypeGeneratorOptions extends BaseGeneratorOptions {
  outputFormat?: OutputFormat;
  blocksRendererInstalled?: boolean;
}

/**
 * Service generator options
 */
export interface ServiceGeneratorOptions extends BaseGeneratorOptions {
  outputFormat?: OutputFormat;
  typesImportPath: string;
}

/**
 * Client generator options
 */
export interface ClientGeneratorOptions extends BaseGeneratorOptions {
  outputFormat?: OutputFormat;
  apiPrefix?: string;
}

/**
 * Actions generator options (framework-specific)
 */
export interface ActionsGeneratorOptions extends BaseGeneratorOptions {
  framework: Framework;
  servicesImportPath: string;
}

/**
 * Generator context passed to all generators
 */
export interface GeneratorContext {
  schema: ParsedSchema;
  options: BaseGeneratorOptions;
  outputFormat: OutputFormat;
  strapiVersion: StrapiVersion;
}

/**
 * Generator result
 */
export interface GeneratorResult {
  files: string[];
  warnings?: string[];
}

/**
 * Re-export core types for convenience
 */
export type { ParsedSchema };
