import path from 'node:path';
import type { StrapiLocale } from '@strapi-integrate/core';
import { formatCode } from '../utils/formatter.js';
import { writeFile, ensureDir } from '../utils/file.js';

export interface LocalesGeneratorOptions {
  outputDir: string;
}

/**
 * Generate locales file from Strapi i18n configuration
 */
export async function generateLocales(
  locales: StrapiLocale[],
  options: LocalesGeneratorOptions
): Promise<string[]> {
  const { outputDir } = options;
  const generatedFiles: string[] = [];

  await ensureDir(outputDir);

  const filePath = path.join(outputDir, 'locales.ts');
  const content = generateLocalesFile(locales);
  await writeFile(filePath, await formatCode(content));
  generatedFiles.push(filePath);

  return generatedFiles;
}

/**
 * Generate the locales file content
 */
function generateLocalesFile(locales: StrapiLocale[]): string {
  if (locales.length === 0) {
    return `/**
 * Strapi Locales
 * Generated by strapi-integrate
 *
 * Note: No locales found. i18n might not be enabled in Strapi.
 */

export const locales = [] as const;

export type Locale = string;

export const defaultLocale: Locale = 'en';

export const localeNames: Record<string, string> = {};
`;
  }

  const defaultLocale = locales.find(l => l.isDefault)?.code || locales[0]?.code || 'en';
  const localeCodes = locales.map(l => `'${l.code}'`).join(' | ');
  const localeArray = locales.map(l => `'${l.code}'`).join(', ');
  const localeNames = locales.map(l => `  '${l.code}': '${l.name}'`).join(',\n');

  return `/**
 * Strapi Locales
 * Generated by strapi-integrate
 */

/**
 * Available locale codes
 */
export const locales = [${localeArray}] as const;

/**
 * Locale type - union of all available locales
 */
export type Locale = ${localeCodes};

/**
 * Default locale
 */
export const defaultLocale: Locale = '${defaultLocale}';

/**
 * Locale display names
 */
export const localeNames: Record<Locale, string> = {
${localeNames}
};

/**
 * Check if a string is a valid locale
 */
export function isValidLocale(code: string): code is Locale {
  return locales.includes(code as Locale);
}

/**
 * Get locale name by code
 */
export function getLocaleName(code: Locale): string {
  return localeNames[code] || code;
}
`;
}
