import path from 'node:path';
import { formatCode } from '../utils/formatter.js';
import { writeFile, ensureDir } from '../utils/file.js';

export interface ClientGeneratorOptions {
  outputDir: string;
}

/**
 * Generate the Strapi client file
 */
export async function generateClient(
  options: ClientGeneratorOptions
): Promise<string[]> {
  const { outputDir } = options;
  const generatedFiles: string[] = [];

  await ensureDir(outputDir);

  const filePath = path.join(outputDir, 'client.ts');
  const content = generateClientFile();
  await writeFile(filePath, await formatCode(content));
  generatedFiles.push(filePath);

  return generatedFiles;
}

/**
 * Generate the client file content
 */
function generateClientFile(): string {
  return `/**
 * Strapi Client
 * Generated by strapi-integrate
 */

import Strapi from 'strapi-sdk-js';

// Initialize the Strapi client
const strapiUrl = import.meta.env.STRAPI_URL || process.env.STRAPI_URL;
const strapiToken = import.meta.env.STRAPI_TOKEN || process.env.STRAPI_TOKEN;

if (!strapiUrl) {
  throw new Error('STRAPI_URL environment variable is required');
}

export const strapi = new Strapi({
  url: strapiUrl,
  axiosOptions: {
    headers: strapiToken ? {
      Authorization: \`Bearer \${strapiToken}\`,
    } : {},
  },
});

// Helper to get typed collection
export function collection<T>(pluralName: string) {
  return {
    async find(params?: Record<string, unknown>) {
      const response = await strapi.find<T[]>(pluralName, params);
      return {
        data: response.data || [],
        meta: response.meta || { pagination: { page: 1, pageSize: 25, pageCount: 1, total: 0 } },
      };
    },
    async findOne(documentId: string, params?: Record<string, unknown>) {
      const response = await strapi.findOne<T>(pluralName, documentId, params);
      return { data: response.data };
    },
    async create(data: { data: Partial<T> }) {
      const response = await strapi.create<T>(pluralName, data.data);
      return { data: response.data };
    },
    async update(documentId: string, data: { data: Partial<T> }) {
      const response = await strapi.update<T>(pluralName, documentId, data.data);
      return { data: response.data };
    },
    async delete(documentId: string) {
      await strapi.delete(pluralName, documentId);
    },
  };
}

// Helper to get typed single type
export function single<T>(singularName: string) {
  return {
    async find(params?: Record<string, unknown>) {
      const response = await strapi.find<T>(singularName, params);
      return { data: response.data };
    },
    async update(data: { data: Partial<T> }) {
      const response = await strapi.update<T>(singularName, 1 as any, data.data);
      return { data: response.data };
    },
    async delete() {
      await strapi.delete(singularName, 1 as any);
    },
  };
}

// Attach helpers to strapi instance
strapi.collection = collection;
strapi.single = single;

// Extend the Strapi type
declare module 'strapi-sdk-js' {
  interface Strapi {
    collection: typeof collection;
    single: typeof single;
  }
}
`;
}
